//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenMinhHung_2001230322_Bai10.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBanSachEntities : DbContext
    {
        public QLBanSachEntities()
            : base("name=QLBanSachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_ChiTiet> tbl_ChiTiet { get; set; }
        public DbSet<tbl_HoaDon> tbl_HoaDon { get; set; }
        public DbSet<tbl_KhachHang> tbl_KhachHang { get; set; }
        public DbSet<tbl_SanPham> tbl_SanPham { get; set; }
    }
}
