//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenMinhHung_2001230322_Bai10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SanPham
    {
        public tbl_SanPham()
        {
            this.tbl_ChiTiet = new HashSet<tbl_ChiTiet>();
        }
    
        public int MaSanPham { get; set; }
        public string TenSP { get; set; }
        public decimal DonGia { get; set; }
        public string HinhAnh { get; set; }
        public string MoTa { get; set; }
        public int SoLuongTon { get; set; }
        public byte TrangThai { get; set; }
    
        public virtual ICollection<tbl_ChiTiet> tbl_ChiTiet { get; set; }
    }
}
