//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenMinhHung_2001230322_Bai10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KhachHang
    {
        public tbl_KhachHang()
        {
            this.tbl_HoaDon = new HashSet<tbl_HoaDon>();
        }
    
        public int MaKhachHang { get; set; }
        public string TenKH { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string MatKhau { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual ICollection<tbl_HoaDon> tbl_HoaDon { get; set; }
    }
}
