//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenMinhHung_2001230322_Bai10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HoaDon
    {
        public tbl_HoaDon()
        {
            this.tbl_ChiTiet = new HashSet<tbl_ChiTiet>();
        }
    
        public int MaHoaDon { get; set; }
        public System.DateTime NgayHoaDon { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public int MaKH { get; set; }
    
        public virtual ICollection<tbl_ChiTiet> tbl_ChiTiet { get; set; }
        public virtual tbl_KhachHang tbl_KhachHang { get; set; }
    }
}
